# Generated by Django 4.0.5 on 2022-07-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.CharField(max_length=500),
        ),
    ]
